# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_positionclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='img',
            field=models.ImageField(default='pass', upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prix',
            name='about',
            field=models.CharField(default=1.5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prix',
            name='name',
            field=models.CharField(default=1.5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prix',
            name='valeur',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
    ]
