# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-07 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_auto_20190407_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=20)),
                ('datejoind', models.DateTimeField(auto_now_add=True, verbose_name='date joind')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Categorie')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='reservation',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.Categorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joind'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='posclient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.PositionClient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='posworker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.PositionWorker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='tache',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='positionworker',
            name='currentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Worker'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resworker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.Worker'),
            preserve_default=False,
        ),
    ]
