# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190407_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='desc',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
