# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_worker_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='img',
            field=models.ImageField(default='ali', upload_to='upload/'),
            preserve_default=False,
        ),
    ]
