# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='1234', max_length=20),
            preserve_default=False,
        ),
    ]
